"""rename address

Revision ID: 6e98ba06ee90
Revises: 81af1007c61b
Create Date: 2024-05-22 20:22:42.808779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e98ba06ee90'
down_revision = '81af1007c61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
    #     batch_op.drop_column('address')
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
    #     batch_op.drop_column('location')
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
